import {
  OF_BLUEPRINT_SECTION_DSL_HEADER,
  OF_BLUEPRINT_SECTION_DSL_RULES,
  OF_BLUEPRINT_SECTION_DSL_SECTION_FORMS
} from '@shared/Orchestraflow-types'

export function buildDslSyntaxPrompt(): string {
  return [
    '## DSL 语法与格式',
    `- 固定头部: ${OF_BLUEPRINT_SECTION_DSL_HEADER}`,
    ...OF_BLUEPRINT_SECTION_DSL_SECTION_FORMS.map((item) => `- section: ${item}`),
    ...OF_BLUEPRINT_SECTION_DSL_RULES.map((rule) => `- 规则: ${rule}`),
    '',
    '## LLM 强制写法提醒',
    '- 不要把 `outputs`、`edges`、`inputs`、`vars`、`let` 这类数组拆成多行条目。',
    '- OFT/1 里的数组和值对象必须写在同一条 `key = ...` 语句里，整体保持单行合法 JSON。',
    '- 如果对象内部需要引用变量，引用值写成 JSON 字符串 `"@ref"`，不要拆成多行键值对。',
    '- 一旦写成多行数组项或多行对象项，parser 会把这些行当成独立语句并报错。',
    '- 普通控制边只能写成 `上游.source -> 下游.target`，不要写成 `上游.output -> 下游.input`。',
    '',
    '## 禁止示例',
    'outputs = [',
    '  "final_content:string <- @refine_loop.result",',
    '  "audit_report:object <- {\\"score\\": \\"@audit.score\\"}"',
    ']',
    '',
    'edges = [',
    '  "start.source -> end.target"',
    ']',
    '',
    '## 正确示例',
    'outputs = ["final_content:string <- @refine_loop.result", "audit_report:object <- {\\"score\\": \\"@audit.score\\"}"]',
    'edges = ["start.source -> end.target"]',
    '',
    '## 最小模板',
    '[workflow]',
    'name = "demo_flow"',
    '',
    '[node.start]',
    'type = "start"',
    'inputs = ["user_query"]',
    '',
    '[node.end]',
    'type = "end"',
    'outputs = ["result:string <- @start.user_query"]',
    '',
    '[graph]',
    'edges = ["start.source -> end.target"]',
    '',
    '## 重要边界',
    '- 这里仅定义语法和格式，不负责节点字段 spec、变量语义、handle/link 语义。',
    '- 节点字段与系统底层规则必须以“声明节点 Spec”和“系统底层机制规则”为准。'
  ].join('\n')
}
